name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: week1/package-lock.json
    - run: npm ci
      working-directory: week1
    - run: npm run build --if-present
      working-directory: week1
    - run: npm test
      working-directory: week1

    - name: Jest coverage report
      if: matrix.node-version == '22.x'
      uses: ArtiomTr/jest-coverage-report-action@v2.3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: week1
