name: Node.js CI
on:
  push:
    branches: ["main"]
    # paths: ["api/**"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    defaults:
      run:
        working-directory: week1
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: week1/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: week1
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./week1
